[build]
  command = "npm run generate"
  publish = "dist"
  functions = "dist/functions"

[[redirects]]
  from = "/fetchurl"
  to = "/.netlify/functions/fetchurl"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
